from Custom_Widgets.widgets.loading.QCustomArcLoader import QCustomArcLoader
from Custom_Widgets.widgets.loading.QCustom3CirclesLoader import QCustom3CirclesLoader
from Custom_Widgets.widgets.loading.QCustomPerlinLoader import QCustomPerlinLoader
from Custom_Widgets.widgets.loading.QCustomQProgressBar import QCustomQProgressBar
from Custom_Widgets.widgets.loading.QCustomSpinner import QCustomSpinner

