# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from Custom_Widgets.widgets.charts.qtcharts.QCustomChartBase import QCustomChartBase
from Custom_Widgets.widgets.charts.qtcharts.QCustomChartProps import AxisChartProps, ChartCommonProps, ChartDataProps, SeriesStyleProps
from PySide6.QtCore import Signal
from typing import Any, ClassVar


class QCustomLineChart(QCustomChartBase, AxisChartProps, SeriesStyleProps, ChartCommonProps, ChartDataProps):
    dataPointClicked: ClassVar[Signal]
    dataPointHovered: ClassVar[Signal]
    seriesAdded: ClassVar[Signal]
    seriesRemoved: ClassVar[Signal]
    chartExportComplete: ClassVar[Signal]
    legendPositionChanged: ClassVar[Signal]
    fillOpacity: float
    def __init__(self, parent = ...) -> None: ...
    def generateExampleData(self, example_type: str = ...): ...
    def updateChart(self): ...
    def addSeries(self, name: str, data: Any, color: Any = ..., visible: bool = ..., line_style: str = ..., line_width: float = ..., marker_style: str = ..., marker_size: float = ..., **kwargs): ...
    def removeSeries(self, name: str): ...
    def updateSeriesData(self, name: str, data: Any): ...
    def appendToSeries(self, name: str, points: Any): ...
    def setSeriesLineStyle(self, name: str, style: str) -> None: ...
    def setSeriesMarkerStyle(self, name: str, style: str) -> None: ...
    def setSeriesLineWidth(self, name: str, width: float) -> None: ...
    def setSeriesMarkerSize(self, name: str, size: float) -> None: ...
    def setXAxisTitle(self, title: str) -> None: ...
    def setYAxisTitle(self, title: str) -> None: ...
    def setXAxisRange(self, min_val: float, max_val: float) -> None: ...
    def setYAxisRange(self, min_val: float, max_val: float) -> None: ...
    def getXAxisRange(self): ...
    def getYAxisRange(self): ...
    def clearData(self): ...
    def getSeriesNames(self): ...
    def getSeriesData(self, name: str): ...
    def setSeriesColor(self, name: str, color: Any): ...
    def setSeriesVisibility(self, name: str, visible: bool): ...
    def setChartTitle(self, title: str) -> None: ...
    def getSeriesLineStyle(self, name: str): ...
    def getSeriesMarkerStyle(self, name: str): ...
    def getSeriesMarkerSize(self, name: str): ...
    def hasCustomMarkerSize(self, series_name: str): ...
    def setAllMarkersSize(self, size: float) -> None: ...
    def resetMarkerSizes(self): ...
    def getMarkerSizeRange(self): ...
    def isValidLineStyle(self, style: str): ...
    def isValidMarkerStyle(self, style: str): ...
    def setCrosshairColor(self, color: Any) -> None: ...
    def setCrosshairWidth(self, width: float) -> None: ...
    def setCrosshairStyle(self, style: Any) -> None: ...
    def showCrosshairAt(self, x: float, y: float): ...
    def hideCrosshair(self): ...
    def showTooltipAt(self, x: float, y: float, series_name: str, title: str = ..., description: str = ...): ...
    def hideTooltip(self): ...
    def setLegendBackgroundVisible(self, visible: bool) -> None: ...
    def setLegendFontSize(self, size: int) -> None: ...
    def getLegendFontSize(self): ...
    def getAvailableLegendPositions(self): ...
    def setLegendAlignment(self, alignment: Any) -> None: ...
    def getLegendAlignment(self): ...
    def getAvailableThemes(self): ...
    def applyCustomPalette(self, palette: Any): ...
    def refreshTheme(self): ...
    def exportToFile(self, format: str = ..., filename: str = ...): ...
    def exportToClipboard(self): ...
    def printChart(self): ...
