# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from Custom_Widgets.widgets.charts.qtcharts.QCustomChartBase import QCustomChartBase
from Custom_Widgets.widgets.charts.qtcharts.QCustomChartProps import ChartCommonProps, ChartDataProps
from PySide6.QtCore import Signal
from typing import Any, ClassVar


class QCustomPieChart(QCustomChartBase, ChartCommonProps, ChartDataProps):
    sliceClicked: ClassVar[Signal]
    sliceHovered: ClassVar[Signal]
    sliceExploded: ClassVar[Signal]
    seriesAdded: ClassVar[Signal]
    seriesRemoved: ClassVar[Signal]
    chartExportComplete: ClassVar[Signal]
    legendPositionChanged: ClassVar[Signal]
    showPercentages: bool
    showValues: bool
    showLegend: bool
    showLabels: bool
    labelsPosition: int
    showPercentLabels: bool
    hatchCsv: str
    hatchPattern: str
    explosionDistance: float
    holeSize: float
    startAngle: float
    endAngle: float
    semicircleEnabled: bool
    pieAngularSpan: float
    semicircleOrientation: str
    gradientFill: bool
    gradientType: str
    borderWidth: float
    borderColor: str
    legendMarkerBorderWidth: float
    explodeOnHover: bool
    hoverExplosionDistance: float
    def __init__(self, parent = ...) -> None: ...
    def generateExampleData(self, example_type: str = ...): ...
    def updateChart(self): ...
    def setShowPercentLabels(self, on) -> None: ...
    def setHatchIndices(self, indices) -> None: ...
    def setHatchPattern(self, name) -> None: ...
    def addSeries(self, name: str, data: Any, color: Any = ..., visible: bool = ..., colors: Any = ..., **kwargs): ...
    def setSliceColors(self, series_name: str, colors: Any) -> None: ...
    def removeSeries(self, name: str): ...
    def updateSeriesData(self, name: str, data: Any): ...
    def addSlice(self, series_name: str, slice_name: str, value: float): ...
    def removeSlice(self, series_name: str, slice_name: str): ...
    def updateSliceValue(self, series_name: str, slice_name: str, new_value: float): ...
    def getSliceNames(self, series_name: str): ...
    def getSliceValue(self, series_name: str, slice_name: str): ...
    def getTotalValue(self, series_name: str): ...
    def getPercentage(self, series_name: str, slice_name: str): ...
    def explodeSlice(self, slice_name: str, explode: bool = ...): ...
    def toggleSliceExplosion(self, slice_name: str): ...
    def explodeAllSlices(self, explode: bool = ...): ...
    def isSliceExploded(self, slice_name: str): ...
    def setExplosionDistance(self, distance: float) -> None: ...
    def getExplosionDistance(self): ...
    def setHoleSize(self, size: float) -> None: ...
    def getHoleSize(self): ...
    def setStartAngle(self, angle: float) -> None: ...
    def getStartAngle(self): ...
    def setEndAngle(self, angle: float) -> None: ...
    def getEndAngle(self): ...
    def setSemicircleEnabled(self, enabled: bool) -> None: ...
    def isSemicircleEnabled(self): ...
    def setPieAngularSpan(self, span: float) -> None: ...
    def getPieAngularSpan(self): ...
    def setSemicircleOrientation(self, orientation: str) -> None: ...
    def getSemicircleOrientation(self): ...
    def setLabelsVisible(self, visible: bool) -> None: ...
    def areLabelsVisible(self): ...
    def setLabelsPosition(self, position: str) -> None: ...
    def getLabelsPosition(self): ...
    def setShowPercentages(self, show: bool) -> None: ...
    def setShowValues(self, show: bool) -> None: ...
    def setGradientFill(self, enabled: bool) -> None: ...
    def isGradientFillEnabled(self): ...
    def setGradientType(self, gradient_type: str) -> None: ...
    def getGradientType(self): ...
    def setBorderWidth(self, width: float) -> None: ...
    def getBorderWidth(self): ...
    def setBorderColor(self, color: Any) -> None: ...
    def getBorderColor(self): ...
    def setLegendMarkerBorderWidth(self, width: float) -> None: ...
    def getLegendMarkerBorderWidth(self): ...
    def setExplodeOnHover(self, enabled: bool) -> None: ...
    def isExplodeOnHoverEnabled(self): ...
    def setHoverExplosionDistance(self, distance: float) -> None: ...
    def getHoverExplosionDistance(self): ...
    def clearData(self): ...
    def clearAllData(self): ...
    def getSeriesNames(self): ...
    def setSeriesColor(self, name: str, color: Any): ...
    def setSeriesVisibility(self, name: str, visible: bool): ...
    def setChartTitle(self, title: str) -> None: ...
    def getSeriesData(self, name: str): ...
    def showTooltipAt(self, x: float, y: float, slice_name: str, title: str = ..., description: str = ...): ...
    def hideTooltip(self): ...
    def setLegendBackgroundVisible(self, visible: bool) -> None: ...
    def setLegendFontSize(self, size: int) -> None: ...
    def getLegendFontSize(self): ...
    def getAvailableLegendPositions(self): ...
    def setLegendAlignment(self, alignment: Any) -> None: ...
    def getLegendAlignment(self): ...
    def getAvailableThemes(self): ...
    def applyCustomPalette(self, palette: Any): ...
    def refreshTheme(self): ...
    def exportToFile(self, format: str = ..., filename: str = ...): ...
    def exportToClipboard(self): ...
    def printChart(self): ...
