# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from Custom_Widgets.widgets.charts.qtcharts.QCustomChartBase import QCustomChartBase
from Custom_Widgets.widgets.charts.qtcharts.QCustomChartProps import AxisChartProps, ChartCommonProps, ChartDataProps
from PySide6.QtCore import Signal
from typing import Any, ClassVar


class QCustomBarChart(QCustomChartBase, AxisChartProps, ChartCommonProps, ChartDataProps):
    barClicked: ClassVar[Signal]
    barHovered: ClassVar[Signal]
    seriesAdded: ClassVar[Signal]
    seriesRemoved: ClassVar[Signal]
    chartExportComplete: ClassVar[Signal]
    legendPositionChanged: ClassVar[Signal]
    showGrid: bool
    gridColor: str
    showLegend: bool
    barWidth: float
    stacked: bool
    showValueLabels: bool
    valueLabelsFormat: str
    labelsPosition: int
    def __init__(self, parent = ...) -> None: ...
    def generateExampleData(self, example_type: str = ...): ...
    def updateChart(self): ...
    def setBarCornerRadius(self, radius: int) -> None: ...
    def getBarCornerRadius(self): ...
    def setBarColors(self, colors, series_name: str = ...) -> None: ...
    def highlightIndex(self, index: int, color = ..., series_name: str = ...): ...
    def clearHighlight(self, series_name: str = ...): ...
    def clearBarColors(self, series_name: str = ...): ...
    def setGridLineColor(self, color, alpha: Any = ...) -> None: ...
    def setGridLineAlpha(self, alpha: int) -> None: ...
    def addSeries(self, name: str, values: Any, categories: Any = ..., color: Any = ..., visible: bool = ...): ...
    def setCategories(self, categories: Any) -> None: ...
    def getCategories(self): ...
    def setXAxisTitle(self, title: str) -> None: ...
    def setYAxisTitle(self, title: str) -> None: ...
    def setYAxisRange(self, min_val: float, max_val: float) -> None: ...
    def getYAxisRange(self): ...
    def clearData(self): ...
    def getSeriesNames(self): ...
    def getSeriesData(self, name: str): ...
    def setSeriesColor(self, name: str, color: Any): ...
    def setSeriesVisibility(self, name: str, visible: bool): ...
    def setChartTitle(self, title: str) -> None: ...
    def removeSeries(self, name: str): ...
    def updateSeriesData(self, name: str, values: Any): ...
    def appendToSeries(self, name: str, values: Any): ...
    def setBarWidth(self, width: float) -> None: ...
    def getBarWidth(self): ...
    def setStacked(self, stacked: bool) -> None: ...
    def isStacked(self): ...
    def setShowValueLabels(self, show: bool) -> None: ...
    def getShowValueLabels(self): ...
    def setValueLabelsFormat(self, format_str: str) -> None: ...
    def getValueLabelsFormat(self): ...
    def setLabelsPosition(self, position: str) -> None: ...
    def getLabelsPosition(self): ...
    def getBarSet(self, series_name: str): ...
    def highlightBar(self, category: str, series_name: str, highlight: bool = ...): ...
    def setCrosshairColor(self, color: Any) -> None: ...
    def setCrosshairWidth(self, width: float) -> None: ...
    def setCrosshairStyle(self, style: Any) -> None: ...
    def showCrosshairAt(self, x: float, y: float): ...
    def hideCrosshair(self): ...
    def showTooltipAt(self, x: float, y: float, series_name: str, title: str = ..., description: str = ...): ...
    def hideTooltip(self): ...
    def setLegendBackgroundVisible(self, visible: bool) -> None: ...
    def setLegendFontSize(self, size: int) -> None: ...
    def getLegendFontSize(self): ...
    def getAvailableLegendPositions(self): ...
    def setLegendAlignment(self, alignment: Any) -> None: ...
    def getLegendAlignment(self): ...
    def getAvailableThemes(self): ...
    def applyCustomPalette(self, palette: Any): ...
    def refreshTheme(self): ...
    def exportToFile(self, format: str = ..., filename: str = ...): ...
    def exportToClipboard(self): ...
    def printChart(self): ...
