# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomMediaTimeline(QWidget):
    positionChanged: ClassVar[Signal]
    clipMoved: ClassVar[Signal]
    clipTrimmed: ClassVar[Signal]
    clipClicked: ClassVar[Signal]
    playToggled: ClassVar[Signal]
    duration: Any
    position: Any
    playing: bool
    loop: bool
    bgColor: str
    rulerColor: str
    playheadColor: str
    trackBgColor: str
    clipColor: str
    waveColor: str
    textColor: str
    cornerRadius: int
    def __init__(self, parent = ...) -> None: ...
    def setPlaying(self, on) -> None: ...
    def play(self): ...
    def pause(self): ...
    def togglePlay(self): ...
    def isPlaying(self): ...
    def setDuration(self, seconds) -> None: ...
    def setPosition(self, seconds) -> None: ...
    def positionSeconds(self): ...
    def addTrack(self, name = ..., kind = ..., color = ...): ...
    def addClip(self, track, start, end, color = ..., label = ...): ...
    def setWaveform(self, track, values) -> None: ...
    def clear(self): ...
    def setTimeline(self, data) -> None: ...
    def paintEvent(self, e): ...
    def mousePressEvent(self, e): ...
    def mouseMoveEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
    def leaveEvent(self, e): ...
    def sizeHint(self): ...
