# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomSegmentedControl(QWidget):
    currentChanged: ClassVar[Signal]
    def __init__(self, parent = ...) -> None: ...
    def setSegments(self, items) -> None: ...
    def count(self): ...
    def currentIndex(self): ...
    def currentData(self): ...
    def setCurrentIndex(self, index) -> None: ...
