# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomDonut(QWidget):
    mode: str
    valuesCsv: str
    colorsCsv: str
    holeRatio: float
    maxSweep: float
    gapDegrees: float
    trackColor: Any
    gapColor: Any
    showPercentLabels: bool
    percentLabelColor: str
    percentPill: bool
    percentPillColor: str
    minLabelPercent: float
    hatchCsv: str
    hatchPattern: str
    def __init__(self, parent = ..., values = ..., colors = ...) -> None: ...
    def setData(self, values, colors = ...) -> None: ...
    def setColors(self, colors) -> None: ...
    def setTrackColor(self, color) -> None: ...
    def setGapColor(self, color) -> None: ...
    def setMode(self, mode) -> None: ...
    def setShowPercentLabels(self, on) -> None: ...
    def setHatchIndices(self, indices) -> None: ...
    def setHatchPattern(self, name) -> None: ...
    def values(self): ...
    def paintEvent(self, e): ...
