# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtGui import QSyntaxHighlighter
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomCodeEditor(QWidget):
    lang: Any
    theme: Any
    def __init__(self, parent = ...) -> None: ...
    def setTheme(self, theme) -> None: ...
    def setLang(self, lang) -> None: ...
    def loadFile(self, filepath, encoding = ...): ...
    def paintEvent(self, event): ...


class QCustomSyntaxHighlighter(QSyntaxHighlighter):
    def __init__(self, document, lang = ..., theme = ...) -> None: ...
    def formatThemeKey(self, color, style = ..., returnColor = ...): ...
    def setTheme(self, theme) -> None: ...
    def setLang(self, lang) -> None: ...
    def setRules(self) -> None: ...
    def highlightBlock(self, text): ...
    def match_multiline(self, text, delimiter, in_state, style): ...
