# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QScrollArea
from typing import Any, ClassVar


class QTagEdit(QScrollArea):
    tagColor: Any
    tagTextColor: Any
    def __init__(self, parent: Any = ..., tag_suggestions: Any = ...) -> None: ...
    def focusInEvent(self, a0: Any): ...
    def addTag(self, text: str): ...
    def clear(self, input = ...): ...
    def enableCheckForDoubles(self, check_for_doubles): ...
    def enableTagSuggestions(self, tag_suggestions: bool): ...
    def onDoubledTag(self, text: str): ...
    def removeTag(self, tag: str): ...
    def setTags(self, tags: Any) -> None: ...
    def setTagSuggestions(self, suggestions: Any) -> None: ...
    def tags(self): ...
