# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomRadialLines(QWidget):
    seriesHovered: ClassVar[Signal]
    pointClicked: ClassVar[Signal]
    seriesCsv: str
    labelsCsv: str
    colorsCsv: str
    maxValue: float
    startAngle: int
    clockwise: bool
    rings: int
    lineWidth: float
    fillOpacity: float
    closed: bool
    smooth: bool
    showGrid: bool
    showMarkers: bool
    showLabels: bool
    showLegend: bool
    gridColor: str
    labelColor: str
    def __init__(self, parent = ..., series = ..., labels = ...) -> None: ...
    def addSeries(self, name, values, color = ...): ...
    def setSeries(self, series) -> None: ...
    def series(self): ...
    def seriesCount(self): ...
    def clearSeries(self): ...
    def setLabels(self, labels) -> None: ...
    def labels(self): ...
    def sampleCount(self): ...
    def seriesColor(self, index): ...
    def maximum(self): ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def pointFor(self, seriesIndex, sampleIndex): ...
    def paintEvent(self, e): ...
    def sampleAt(self, pos): ...
    def seriesAt(self, pos): ...
    def mouseMoveEvent(self, e): ...
    def leaveEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
