# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomFileDropZone(QWidget):
    filesDropped: ClassVar[Signal]
    filesChanged: ClassVar[Signal]
    def __init__(self, parent = ..., multiple = ..., extensions = ...) -> None: ...
    def dragEnterEvent(self, e): ...
    def dragLeaveEvent(self, e): ...
    def dropEvent(self, e): ...
    def mousePressEvent(self, e): ...
    def files(self): ...
    def clear(self): ...
    def setAcceptedExtensions(self, extensions) -> None: ...
    def setMultiple(self, multiple) -> None: ...
