# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomHamburgerMenu(QWidget):
    acrylicEnabled: Any
    acrylicBlurRadius: Any
    acrylicTintColor: Any
    acrylicLuminosityColor: Any
    acrylicNoiseOpacity: Any
    position: Any
    animationDuration: Any
    animationEasingCurve: Any
    menuWidth: Any
    menuHeight: Any
    sizeWrap: Any
    center: Any
    margin: Any
    backgroundColor: Any
    shadowColor: Any
    shadowBlurRadius: Any
    cornerRadius: Any
    autoHide: Any
    overlayColor: Any
    toggleButtonName: Any
    showButtonName: Any
    hideButtonName: Any
    def __init__(self, parent = ...) -> None: ...
    def adjustSizeToContent(self): ...
    def showMenu(self): ...
    def hideMenu(self, duration = ...): ...
    def toggleMenu(self): ...
    def getButtonByName(self, buttonName): ...
    def getWidget(self, name: str): ...
    def event(self, event): ...
    def paintEvent(self, paintEvent: Any): ...
    def showEvent(self, event: Any): ...
    def eventFilter(self, obj, event): ...


class QHamburgerMenuOverlay(QWidget):
    def __init__(self, parent = ...) -> None: ...
    def setParent(self, parent): ...
    def updateOverlayColor(self): ...
    def updateAcrylicEffect(self): ...
    def eventFilter(self, obj, event): ...
    def paintEvent(self, event): ...
    def mousePressEvent(self, event): ...
    def showEvent(self, event): ...
    def resizeEvent(self, event): ...
