# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomAgendaList(QWidget):
    itemClicked: ClassVar[Signal]
    itemsJson: str
    rowHeight: int
    railColor: str
    doneColor: str
    activeColor: str
    pendingColor: str
    titleColor: str
    subtitleColor: str
    timeColor: str
    activeBgColor: str
    showRail: bool
    def __init__(self, parent = ..., items = ...) -> None: ...
    def setItems(self, items) -> None: ...
    def items(self): ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def heightForWidth(self, w): ...
    def paintEvent(self, e): ...
    def mouseMoveEvent(self, e): ...
    def leaveEvent(self, e): ...
    def mousePressEvent(self, e): ...
