# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomProgressIndicator(QWidget):
    color: Any
    fillColor: Any
    successFillColor: Any
    warningFillColor: Any
    errorFillColor: Any
    formProgressCount: Any
    formProgressHeight: Any
    formProgressAnimationDuration: Any
    def __init__(self, parent = ...) -> None: ...
    def selectFormProgressIndicatorTheme(self, themeNumber): ...
    def setStepStatus(self, **stepStatus) -> None: ...
    def updateFormProgressIndicator(self, **values): ...
    def animateFormProgress(self, percentage): ...
    def updateFormProgress(self, value): ...
    def createFormProgressIndicator(self): ...
    def paintEvent(self, event: Any): ...


class Test(object):
    def main(self): ...
