# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomPagination(QWidget):
    pageChanged: ClassVar[Signal]
    def __init__(self, parent = ..., pageCount = ...) -> None: ...
    def pageCount(self): ...
    def setPageCount(self, count) -> None: ...
    def currentPage(self): ...
    def setCurrentPage(self, page) -> None: ...
