# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomSankey(QWidget):
    linkHovered: ClassVar[Signal]
    nodeHovered: ClassVar[Signal]
    nodeClicked: ClassVar[Signal]
    linksCsv: str
    nodeColorsCsv: str
    nodeWidth: int
    nodePadding: int
    linkOpacity: float
    curvature: float
    showLabels: bool
    showValues: bool
    labelColor: str
    def __init__(self, parent = ..., links = ...) -> None: ...
    def setLinks(self, links) -> None: ...
    def links(self): ...
    def linkCount(self): ...
    def clearLinks(self): ...
    def nodes(self): ...
    def nodeDepth(self, name): ...
    def nodeDepths(self): ...
    def nodeValue(self, name): ...
    def columns(self): ...
    def nodeColor(self, name): ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def isSink(self, name): ...
    def nodeRects(self): ...
    def ribbons(self): ...
    def paintEvent(self, e): ...
    def nodeAt(self, pos): ...
    def linkAt(self, pos): ...
    def mouseMoveEvent(self, e): ...
    def leaveEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
