# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomToastManager(object):
    def __init__(self) -> None: ...
    @classmethod
    def instance(cls): ...
    def add(self, toast): ...
    def remove(self, toast): ...
    def stackFor(self, parent, position): ...
    def reflow(self, parent, position): ...


class QCustomToast(QWidget):
    closed: ClassVar[Signal]
    variant: str
    def __init__(self, parent, message, variant = ..., title = ..., duration = ..., closable = ..., position = ...) -> None: ...
    def showToast(self): ...
    def dismiss(self): ...
    @classmethod
    def show_toast(cls, parent, message, variant = ..., **kw): ...
    @classmethod
    def success(cls, parent, message, **kw): ...
    @classmethod
    def error(cls, parent, message, **kw): ...
    @classmethod
    def warning(cls, parent, message, **kw): ...
    @classmethod
    def info(cls, parent, message, **kw): ...
