# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QFrame
from typing import Any, ClassVar


class QCustomChatBubble(QFrame):
    text: str
    side: str
    sender: str  # type: ignore[assignment]
    time: str
    foot: str
    bubbleColor: str
    textColor: str
    metaColor: str
    radius: int
    maxBubbleWidth: int
    def __init__(self, parent = ..., text = ..., side = ...) -> None: ...
    def setText(self, text) -> None: ...
    def setBodyWidget(self, widget) -> None: ...
    def setBodyPadding(self, h, v) -> None: ...
    def setMetaWidget(self, widget) -> None: ...
    def setReactionBar(self, widget) -> None: ...
    def setSender(self, text) -> None: ...
    def setTime(self, text) -> None: ...
    def setFoot(self, text) -> None: ...
