# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomGradientText(QWidget):
    clicked: ClassVar[Signal]
    text: str
    stopsCsv: str
    angle: int
    animated: bool
    animationSpeed: int
    fontScale: float
    bold: bool
    alignment: str
    wordWrap: bool
    def __init__(self, parent = ..., text = ..., stops = ...) -> None: ...
    def setStops(self, stops) -> None: ...
    def stops(self): ...
    def gradientFor(self, rect): ...
    def start(self): ...
    def stop(self): ...
    def isAnimating(self): ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def paintEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
