# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomSwitch(QWidget):
    toggled: ClassVar[Signal]
    checked: bool
    sizeVariant: str
    thumbPosition: Any
    trackOnColor: Any
    trackOffColor: Any
    thumbColor: Any
    def __init__(self, parent = ..., checked = ...) -> None: ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def paintEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
    def keyPressEvent(self, e): ...
    def toggle(self): ...
    def isChecked(self): ...
    def setChecked(self, checked) -> None: ...
