# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomSlideMenu(QWidget):
    onCollapsed: ClassVar[Signal]
    onExpanded: ClassVar[Signal]
    onCollapsing: ClassVar[Signal]
    onExpanding: ClassVar[Signal]
    def __init__(self, parent = ...) -> None: ...
    def initializeVariables(self): ...
    def setMinSize(self) -> None: ...
    def customizeQCustomSlideMenu(self, **customValues): ...
    def toggleMenu(self): ...
    def toggle(self): ...
    def activateMenuButton(self, buttonObject): ...
    def toggleButton(self, **values): ...
    def getButtonByName(self, buttonName): ...
    def slideMenu(self): ...
    def expandMenu(self): ...
    def collapseMenu(self): ...
    def emitStatusSignal(self): ...
    def animateMenu(self): ...
    def createAnimation(self, property_name, start_value, end_value): ...
    def determineWith(self): ...
    def determineHeight(self): ...
    def calculateEndWidth(self, width): ...
    def calculateEndHeight(self, height): ...
    def autoContentSize(self): ...
    def adjustMaximumSize(self, property_name): ...
    def refresh(self): ...
    def isExpanded(self): ...
    def isCollapsed(self): ...
    def getDefaultWidth(self): ...
    def getDefaultHeight(self): ...
    def getCollapsedWidth(self): ...
    def getCollapsedHeight(self): ...
    def getExpandedWidth(self): ...
    def getExpandedHeight(self): ...
    def animateDefaultSize(self): ...
    def showEvent(self, event): ...
    def paintEvent(self, event: Any): ...
    def eventFilter(self, obj, event: Any): ...
