# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomTypewriterText(QWidget):
    phraseFinished: ClassVar[Signal]
    cycled: ClassVar[Signal]
    phrasesCsv: str
    typeSpeed: int
    eraseSpeed: int
    holdDelay: int
    loop: bool
    erase: bool
    showCaret: bool
    caretBlinkRate: int
    alignment: str
    textColor: str
    caretColor: str
    def __init__(self, parent = ..., phrases = ..., autoStart = ...) -> None: ...
    def setPhrases(self, phrases, restart = ...) -> None: ...
    def phrases(self): ...
    def currentPhrase(self): ...
    def visibleText(self): ...
    def isRunning(self): ...
    def start(self): ...
    def stop(self): ...
    def skip(self): ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def paintEvent(self, e): ...
