# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomScatterChart(QWidget):
    pointHovered: ClassVar[Signal]
    pointClicked: ClassVar[Signal]
    pointsCsv: str
    seriesColorsCsv: str
    xAxisTitle: str
    yAxisTitle: str
    markerSize: float
    markerShape: str
    markerOpacity: float
    tickCount: int
    showGrid: bool
    showAxes: bool
    showLegend: bool
    showTooltip: bool
    gridColor: str
    axisColor: str
    labelColor: str
    def __init__(self, parent = ..., series = ...) -> None: ...
    def addSeries(self, name, points, color = ...): ...
    def setSeries(self, series) -> None: ...
    def series(self): ...
    def seriesCount(self): ...
    def pointCount(self): ...
    def clearSeries(self): ...
    def removeSeries(self, index): ...
    def seriesColor(self, index): ...
    def dataBounds(self): ...
    def xRange(self): ...
    def yRange(self): ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def mapPoint(self, x, y): ...
    def paintEvent(self, e): ...
    def pointAt(self, pos, tolerance = ...): ...
    def mouseMoveEvent(self, e): ...
    def leaveEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
