# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from Custom_Widgets.widgets.display.QCustomTipOverlay import QCustomTipOverlay
from PySide6.QtCore import Signal
from typing import Any, ClassVar


class QCustomEmojiPicker(QCustomTipOverlay):
    emojiSelected: ClassVar[Signal]
    emojisUpdated: ClassVar[Signal]
    updateFailed: ClassVar[Signal]
    def __init__(self, parent = ..., target = ..., tailPosition = ..., itemsPerRow = ..., performanceSearch = ..., howForm = ..., closeOnSelect = ..., autoUpdate = ..., updateMaxAgeDays = ..., onlineUrl = ..., recentLimit = ...) -> None: ...
    def select(self): ...
    def recentEmojis(self): ...
    def isLocalOutdated(self): ...
    def datasetInfo(self): ...
    def updateEmojisOnline(self, force: bool = ...): ...
    def on_input(self, text: str): ...
    def closeEvent(self, e): ...
