# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomStepper(QWidget):
    currentStepChanged: ClassVar[Signal]
    def __init__(self, parent = ..., orientation = ...) -> None: ...
    def setSteps(self, titles) -> None: ...
    def stepCount(self): ...
    def currentStep(self): ...
    def setCurrentStep(self, index) -> None: ...
    def next(self): ...
    def previous(self): ...
    def isComplete(self): ...
