# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QProgressBar
from typing import Any, ClassVar


class QCustomQProgressBar(QProgressBar):
    shortPos: Any
    longPos: Any
    paused: Any
    customBarColor: Any
    errorColor: Any
    pausedColor: Any
    def __init__(self, parent = ..., start = ...) -> None: ...
    def start(self): ...
    def stop(self): ...
    def isStarted(self): ...
    def pause(self): ...
    def resume(self): ...
    def setPaused(self, isPaused: bool) -> None: ...
    def isPaused(self): ...
    def error(self): ...
    def setError(self, isError: bool) -> None: ...
    def isError(self): ...
    def barColor(self): ...
    def paintEvent(self, e): ...
