# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomDivergingBarChart(QWidget):
    upCsv: str
    downCsv: str
    labelsCsv: str
    upColor: str
    downColor: str
    barWidth: int
    cornerRadius: int
    zeroGap: int
    showAxis: bool
    showLabels: bool
    axisPrefix: str
    axisSuffix: str
    gridColor: str
    axisTextColor: str
    def __init__(self, parent = ..., up = ..., down = ..., labels = ...) -> None: ...
    def setData(self, up, down, labels = ...) -> None: ...
    def setUpValues(self, values) -> None: ...
    def setDownValues(self, values) -> None: ...
    def setLabels(self, labels) -> None: ...
    def setColors(self, up_color, down_color) -> None: ...
    def setTickStep(self, step) -> None: ...
    def upValues(self): ...
    def downValues(self): ...
    def paintEvent(self, e): ...
