# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomRainbowButton(QWidget):
    clicked: ClassVar[Signal]
    text: str
    colorsCsv: str
    borderWidth: int
    cornerRadius: int
    speed: int
    animated: bool
    glow: bool
    filled: bool
    sizeVariant: str
    textColor: str
    surfaceColor: str
    def __init__(self, parent = ..., text = ...) -> None: ...
    def start(self): ...
    def stop(self): ...
    def isAnimating(self): ...
    def showEvent(self, e): ...
    def hideEvent(self, e): ...
    def setColors(self, colors) -> None: ...
    def colors(self): ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def paintEvent(self, e): ...
    def enterEvent(self, e): ...
    def leaveEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
    def keyPressEvent(self, e): ...
