# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomCard(QWidget):
    title: str
    subtitle: str
    def __init__(self, parent = ..., title = ..., subtitle = ...) -> None: ...
    def contentLayout(self): ...
    def body(self): ...
    def addWidget(self, widget): ...
    def addLayout(self, layout): ...
    def setTitle(self, text) -> None: ...
    def setSubtitle(self, text) -> None: ...
