# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomMultiSelect(QWidget):
    selectionChanged: ClassVar[Signal]
    optionToggled: ClassVar[Signal]
    optionsCsv: str
    selectedCsv: str
    placeholderText: str
    maxChips: int
    maxSelection: int
    searchable: bool
    sizeVariant: str
    state: str
    fieldBackgroundColor: Any
    fieldBorderColor: Any
    fieldBorderActiveColor: Any
    fieldBorderErrorColor: Any
    chipBackgroundColor: Any
    chipTextColor: Any
    textColor: Any
    placeholderColor: Any
    def __init__(self, parent = ..., options = ..., selected = ..., placeholder = ...) -> None: ...
    def setOptions(self, options) -> None: ...
    def options(self): ...
    def labelFor(self, value): ...
    def selected(self): ...
    def selectedLabels(self): ...
    def setSelected(self, values) -> None: ...
    def isSelected(self, value): ...
    def selectOption(self, value, on = ...): ...
    def toggleOption(self, value): ...
    def clearSelection(self): ...
    def count(self): ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def paintEvent(self, e): ...
    def showPopup(self): ...
    def hidePopup(self): ...
    def isPopupVisible(self): ...
    def mouseReleaseEvent(self, e): ...
    def keyPressEvent(self, e): ...
