# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomRadialBars(QWidget):
    barHovered: ClassVar[Signal]
    barClicked: ClassVar[Signal]
    barsCsv: str
    colorsCsv: str
    maxValue: float
    startAngle: int
    clockwise: bool
    thickness: int
    spacing: int
    holeRatio: float
    rounded: bool
    showTrack: bool
    showLabels: bool
    showValues: bool
    trackColor: str
    labelColor: str
    def __init__(self, parent = ..., bars = ...) -> None: ...
    def setBars(self, bars) -> None: ...
    def bars(self): ...
    def barCount(self): ...
    def clearBars(self): ...
    def maximum(self): ...
    def barColor(self, index): ...
    def fractionFor(self, index): ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def ringRect(self, index): ...
    def paintEvent(self, e): ...
    def barAt(self, pos): ...
    def mouseMoveEvent(self, e): ...
    def leaveEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
