# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomCardStack(QWidget):
    currentChanged: ClassVar[Signal]
    cardsJson: str
    cardHeight: int
    cardPeek: int
    xInset: int
    maxVisible: int
    currentIndex: int
    animationDuration: int
    def __init__(self, parent = ...) -> None: ...
    def addCard(self, brand = ..., amount = ..., number = ..., top = ..., bottom = ..., variant = ..., textColor = ..., fullNumber = ..., revealable = ...): ...
    def setCards(self, cards) -> None: ...
    def clear(self): ...
    def setCardColors(self, top, bottom = ...) -> None: ...
    def setCardColorsList(self, grads) -> None: ...
    def count(self): ...
    def currentIndexValue(self): ...
    def setCurrentIndex(self, index, animate = ...) -> None: ...
    def next(self): ...
    def previous(self): ...
    def currentCard(self): ...
    def resizeEvent(self, e): ...
    def mousePressEvent(self, e): ...
