# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QComboBox
from typing import Any, ClassVar


class QCustomComboBox(QComboBox):
    variant: str
    sizeVariant: str
    def __init__(self, parent = ..., editable = ...) -> None: ...
    def setEditable(self, editable) -> None: ...
    def placeholderText(self): ...
    def setPlaceholderText(self, text) -> None: ...
    def setItems(self, items) -> None: ...
    def currentValue(self): ...
