# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from Custom_Widgets.components.python.ui_info import Ui_Form
from PySide6.QtCore import QObject, Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class LoadForm(QWidget):
    def __init__(self, form) -> None: ...


class QCustomTipOverlay(QWidget, Ui_Form):
    closed: ClassVar[Signal]
    def __init__(self, title: str = ..., description: str = ..., icon: Any = ..., image: Any = ..., isClosable = ..., target: Any = ..., parent = ..., aniType = ..., deleteOnClose = ..., duration = ..., tailPosition = ..., showForm = ..., addWidget = ..., closeIcon: Any = ..., toolFlag = ..., bgBrush: Any = ...) -> None: ...
    def setShadowEffect(self) -> None: ...
    def handleThemeChanged(self): ...
    def showEvent(self, e): ...
    def closeEvent(self, e): ...
    def eventFilter(self, obj, e: Any): ...
    def paintEvent(self, e: Any): ...
    def setIcon(self, icon) -> None: ...
    def setCloseIcon(self, iconFile) -> None: ...
    def setDescription(self, description) -> None: ...
    def setTitle(self, title) -> None: ...
    def loadForm(self, form): ...
    def addWidget(self, widget): ...
    def adjustSizeToContent(self): ...
    def setClosable(self, clossable: bool = ...) -> None: ...
    def moveButton(self): ...


class QCustomTipOverlayManager(QObject):
    def __init__(self) -> None: ...
    @classmethod
    def register(tipOverlay, name): ...
    @classmethod
    def make(tipOverlay, position: str): ...


class TopTailQCustomQToolTipManager(QCustomTipOverlayManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class BottomTailQCustomQToolTipManager(QCustomTipOverlayManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class LeftTailQCustomQToolTipManager(QCustomTipOverlayManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class RightTailQCustomQToolTipManager(QCustomTipOverlayManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class TopLeftTailQCustomQToolTipManager(TopTailQCustomQToolTipManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class TopRightTailQCustomQToolTipManager(TopTailQCustomQToolTipManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class BottomLeftTailQCustomQToolTipManager(BottomTailQCustomQToolTipManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class BottomRightTailQCustomQToolTipManager(BottomTailQCustomQToolTipManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class LeftTopTailQCustomQToolTipManager(LeftTailQCustomQToolTipManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class LeftBottomTailQCustomQToolTipManager(LeftTailQCustomQToolTipManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class RightTopTailQCustomQToolTipManager(RightTailQCustomQToolTipManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class RightBottomTailQCustomQToolTipManager(RightTailQCustomQToolTipManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class AutoPositionQCustomQToolTipManager(QCustomTipOverlayManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...
    def createManager(self, tipOverlay: Any): ...
    def getTipOverlay(self, tipOverlay: Any): ...


class QCustomQToolTipFilter(QObject):
    def __init__(self, duration = ..., icon = ..., tailPosition = ...) -> None: ...
    def eventFilter(self, obj, event): ...
    def showCustomToolTip(self, text, target): ...
