# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomSocialButton(QWidget):
    clicked: ClassVar[Signal]
    brand: str
    text: str
    iconPath: str
    variant: str
    shape: str
    sizeVariant: str
    iconOnly: bool
    brandColor: str
    surfaceColor: str
    def __init__(self, parent = ..., brand = ..., text = ..., icon = ...) -> None: ...
    def setBrand(self, brand) -> None: ...
    def brandNames(self): ...
    def isKnownBrand(self): ...
    def foregroundColor(self): ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def paintEvent(self, e): ...
    def enterEvent(self, e): ...
    def leaveEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
    def keyPressEvent(self, e): ...
