# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QLabel
from typing import Any, ClassVar


class QCustomBadge(QLabel):
    clicked: ClassVar[Signal]
    variant: str
    sizeVariant: str
    dot: bool
    def __init__(self, text = ..., parent = ..., variant = ...) -> None: ...
    def setText(self, text): ...
    def setCount(self, count, maxCount = ...) -> None: ...
    def setDot(self, on = ...) -> None: ...
    def setShowZero(self, show) -> None: ...
    def count(self): ...
    def isDot(self): ...
    def attachTo(self, target, corner = ..., xOffset = ..., yOffset = ...): ...
    def eventFilter(self, obj, event): ...
    def mousePressEvent(self, event): ...
