# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomFunnelChart(QWidget):
    stageHovered: ClassVar[Signal]
    stageClicked: ClassVar[Signal]
    stagesCsv: str
    colorsCsv: str
    shape: str
    orientation: str
    gapPx: int
    neckRatio: float
    showLabels: bool
    showValues: bool
    showPercent: bool
    percentOf: str
    labelColor: str
    outsideLabelColor: str
    def __init__(self, parent = ..., stages = ...) -> None: ...
    def setStages(self, stages) -> None: ...
    def stages(self): ...
    def stageCount(self): ...
    def clearStages(self): ...
    def maximum(self): ...
    def stageColor(self, index): ...
    def percentFor(self, index): ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def bands(self): ...
    def paintEvent(self, e): ...
    def stageAt(self, pos): ...
    def mouseMoveEvent(self, e): ...
    def leaveEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
