# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomRichTextEditor(QWidget):
    textChanged: ClassVar[Signal]
    def __init__(self, parent = ...) -> None: ...
    def editor(self): ...
    def toHtml(self): ...
    def setHtml(self, html) -> None: ...
    def toPlainText(self): ...
    def setPlainText(self, text) -> None: ...
