# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomFlowWidget(QWidget):
    spacing: Any
    horizontalSpacing: Any
    verticalSpacing: Any
    margin: Any
    animationEnabled: Any
    animationDuration: Any
    animationEasingCurve: Any
    equalDistribution: Any
    autoFillWidth: Any
    autoFillHeight: Any
    justifySpacing: Any
    orderJsonPath: Any
    def __init__(self, parent = ...) -> None: ...
    def adoptExistingChildren(self): ...
    def showEvent(self, event): ...
    def childEvent(self, event): ...
    def addWidget(self, widget, position = ...): ...
    def removeWidget(self, widget): ...
    def clear(self): ...
    def getFlowLayout(self): ...
    def stopAllAnimations(self): ...
    def isAnimating(self): ...
    def refreshLayout(self): ...
    def resizeEvent(self, event): ...
