# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from Custom_Widgets.components.python.ui_dialog import Ui_Form
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QDialog, QWidget
from typing import Any, ClassVar


class QCustomQDialog(QDialog, Ui_Form):
    accepted: ClassVar[Signal]
    rejected: ClassVar[Signal]
    def __init__(self, parent = ..., showForm = ..., title = ..., description = ..., padding = ..., yesButtonIcon = ..., cancelButtonIcon = ..., yesButtonText = ..., cancelButtonText = ..., animationDuration = ..., showYesButton = ..., showCancelButton = ..., setModal = ..., frameless = ..., windowMovable = ..., addWidget = ..., blurBackground = ..., position = ..., closeOnEsc = ..., closeShortcut = ...) -> None: ...
    def addWidget(self, widget, alignment = ...): ...
    def setShadowEffect(self, blurRadius = ..., offset = ..., color = ...) -> None: ...
    def setMovable(self, movable: bool) -> None: ...
    def mousePressEvent(self, event: Any): ...
    def mouseMoveEvent(self, event: Any): ...
    def mouseReleaseEvent(self, event: Any): ...
    def hideYesButton(self): ...
    def hideCancelButton(self): ...
    def keyPressEvent(self, event: Any): ...
    def paintEvent(self, e: Any): ...
    def showEvent(self, e): ...
    def hideEvent(self, e): ...
    def done(self, code): ...
    def resizeEvent(self, e): ...
    def adjustSizeToContent(self): ...
    def adjustToParentSize(self): ...
    def checkAppTheme(self): ...
    def eventFilter(self, obj, e: Any): ...
    def isDark(self): ...


class MaskWidget(QWidget):
    def __init__(self, parent = ..., dialog: Any = ...) -> None: ...
    def resizeEvent(self, event): ...
    def moveEvent(self, event): ...
    def eventFilter(self, obj, event): ...
    def paintEvent(self, e: Any): ...
    def deleteLater(self): ...
    def onParentDestroyed(self): ...
    def showEvent(self, event): ...
    def updateAcrylicEffect(self): ...
    def screenGrab(self): ...
