# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QFrame
from typing import Any, ClassVar


class RoundedRect(object):
    def __init__(self, x = ..., y = ..., w = ..., h = ...) -> None: ...


class QCustom3CirclesLoader(QFrame):
    color: Any
    penWidth: Any
    animationDuration: Any
    def __init__(self, parent = ..., color = ..., penWidth = ..., animationDuration = ...) -> None: ...
    def initRects(self): ...
    def getVariantAnimation(self): ...
    def initMoveDownAnimation(self): ...
    def initMoveRightAnimation(self): ...
    def initMoveUpAnimation(self): ...
    def initMoveLeftAnimation(self): ...
    def moveDownUpdateH(self, newValue): ...
    def moveDownUpdateY(self, newValue): ...
    def moveRightUpdateW(self, newValue): ...
    def moveRightUpdateX(self, newValue): ...
    def moveUpUpdateY(self, newValue): ...
    def moveUpUpdateH(self, newValue): ...
    def moveLeftUpdateX(self, newValue): ...
    def moveLeftUpdateH(self, newValue): ...
    def startAnimations(self): ...
    def finished(self): ...
    def paintEvent(self, e): ...
