# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class LoadForm(QWidget):
    def __init__(self, form) -> None: ...
    def applyThemeIcons(self): ...
    def paintEvent(self, e: Any): ...


class QCustomEmbeddedWindow(QWidget):
    closed: ClassVar[Signal]
    borderRadius: Any
    headerHeight: Any
    animationDuration: Any
    titleText: Any
    def __init__(self, parent, pos = ..., title = ..., icon = ..., borderRadius = ..., headerHeight = ..., animationDuration = ..., showForm = ..., addWidget = ...) -> None: ...
    def addWidget(self, widget): ...
    def animateHeight(self, startHeight, endHeight): ...
    def showHideContent(self): ...
    def showEvent(self, e): ...
    def raiseWidget(self, opacityEffect): ...
    def adjustSizeToContent(self): ...
    def setShadow(self) -> None: ...
    def setTitle(self, text) -> None: ...
    def title(self): ...
    def setControlsVisible(self, b) -> None: ...
    def update(self, *args, **kwargs): ...
    def mousePressEvent(self, event): ...
    def mouseMoveEvent(self, event): ...
    def mouseReleaseEvent(self, event): ...
    def paintEvent(self, event: Any): ...
