# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class ProgressBarArcLoader(object):
    def __init__(self, parent = ..., progress = ..., duration = ...) -> None: ...
    def getProgressAnimation(self, start, end): ...
    def updateProgress(self, newValue): ...


class QCustomRoundProgressBar(QWidget):
    value: Any
    minimum: Any
    maximum: Any
    textVisible: Any
    clockwise: Any
    animationDuration: Any
    progressBarWidth: Any
    progressColor: Any
    progressBaseColor: Any
    textColor: Any
    def __init__(self, parent = ..., progressColor = ..., textColor = ..., progressBarWidth = ...) -> None: ...
    def setValue(self, val) -> None: ...
    def initPen(self, progressBarWidth): ...
    def animateTo(self, progress): ...
    def calculateXR(self): ...
    def draw(self): ...
    def drawText(self): ...
    def paintEvent(self, e): ...
