# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomEmptyState(QWidget):
    actionClicked: ClassVar[Signal]
    def __init__(self, parent = ..., icon = ..., title = ..., description = ...) -> None: ...
    def setIcon(self, glyph_or_pixmap) -> None: ...
    def setTitle(self, title) -> None: ...
    def setDescription(self, description) -> None: ...
    def setActionText(self, text) -> None: ...
    def actionButton(self): ...
