# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomSidebarContainer(QWidget):
    visibilityChanged: ClassVar[Signal]
    hideOnCollapse: Any
    showOnCollapse: Any
    animationDuration: Any
    def __init__(self, parent = ...) -> None: ...
    def startShowAnimation(self): ...
    def startHideAnimation(self): ...
    def onAnimationFinished(self): ...
    def minimumSizeHint(self): ...
    def hideContainer(self): ...
    def showContainer(self): ...
    def hideContainerForce(self): ...
    def showContainerForce(self): ...
    def showEvent(self, e): ...
    def connectToParent(self): ...
    def paintEvent(self, event: Any): ...
