# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import QAbstractTableModel, Signal
from PySide6.QtWidgets import QStyledItemDelegate, QWidget
from typing import Any, ClassVar


class DataTableColumn(object):
    def __init__(self, key, title = ..., type = ..., width = ..., align = ..., formatter = ..., sortable = ..., renderer = ..., color = ..., colorMap = ..., colorKey = ..., subtitleKey = ..., subtitleScale = ..., subtitleBold = ...) -> None: ...
    @classmethod
    def ensure(cls, column): ...
    def defaultAlign(self): ...
    def resolveColor(self, value, row): ...
    def subtitle(self, row): ...


class QCustomDataTableModel(QAbstractTableModel):
    checkedChanged: ClassVar[Signal]
    def __init__(self, columns = ..., rows = ..., parent = ..., selectable = ..., rowActions = ...) -> None: ...
    def rowCount(self, parent = ...): ...
    def columnCount(self, parent = ...): ...
    def data(self, index, role = ...): ...
    def setData(self, index, value, role = ...) -> None: ...
    def headerData(self, section, orientation, role = ...): ...
    def flags(self, index): ...
    def removeRows(self, row, count, parent = ...): ...
    def columns(self): ...
    def setColumns(self, columns) -> None: ...
    def rows(self): ...
    def setRows(self, rows) -> None: ...
    def addRow(self, row): ...
    def addRows(self, rows): ...
    def clear(self): ...
    def rawValue(self, row, col): ...
    def isSelectable(self): ...
    def setSelectable(self, on) -> None: ...
    def rowActions(self): ...
    def setRowActions(self, actions) -> None: ...
    def checkedRows(self): ...
    def setRowChecked(self, row, checked = ...) -> None: ...
    def setAllChecked(self, checked) -> None: ...
    def headerCheckState(self): ...


class QCustomDataTableDelegate(QStyledItemDelegate):
    def __init__(self, parent = ...) -> None: ...
    def setAccentColor(self, color) -> None: ...
    def setMutedColor(self, color) -> None: ...
    def setActionsColor(self, color) -> None: ...
    def setTwoLineSubtitleScale(self, delta) -> None: ...
    def setTwoLineSubtitleBold(self, bold) -> None: ...
    def setStatusDotSize(self, px) -> None: ...
    def paint(self, painter, option, index): ...
    def sizeHint(self, option, index): ...


class QCustomDataTable(QWidget):
    rowSelected: ClassVar[Signal]
    cellClicked: ClassVar[Signal]
    sortChanged: ClassVar[Signal]
    pageChanged: ClassVar[Signal]
    rowActionTriggered: ClassVar[Signal]
    selectionCheckedChanged: ClassVar[Signal]
    headerActionsGlyphClicked: ClassVar[Signal]
    pageSize: int
    showPagination: Any
    selectionMode: str
    selectable: Any
    sortable: Any
    filterable: Any
    alternatingRowColors: Any
    showGrid: Any
    showHeader: Any
    variant: str
    sizeVariant: str
    def __init__(self, parent = ...) -> None: ...
    def eventFilter(self, obj, event): ...
    def setFlexColumn(self, dataColumnIndex) -> None: ...
    def setFlexMinWidth(self, px) -> None: ...
    def setAutoFlex(self, on) -> None: ...
    def setColumns(self, columns) -> None: ...
    def setData(self, rows) -> None: ...
    def setRows(self, rows) -> None: ...
    def addRow(self, row): ...
    def clear(self): ...
    def model(self): ...
    def view(self): ...
    def delegate(self): ...
    def setCellAccentColor(self, color) -> None: ...
    def setCellMutedColor(self, color) -> None: ...
    def setActionsColor(self, color) -> None: ...
    def setTwoLineSubtitleScale(self, delta) -> None: ...
    def setTwoLineSubtitleBold(self, bold) -> None: ...
    def setStatusDotSize(self, px) -> None: ...
    def setPersistentSortIndicators(self, on) -> None: ...
    def setHeaderSelectCaret(self, on) -> None: ...
    def setHeaderActionsGlyph(self, kind) -> None: ...
    def setHeaderGlyphColor(self, color) -> None: ...
    def setHeaderAccentColor(self, color) -> None: ...
    def isSelectable(self): ...
    def setSelectable(self, on) -> None: ...
    def setRowActions(self, actions) -> None: ...
    def rowActions(self): ...
    def checkedRows(self): ...
    def setRowChecked(self, row, checked = ...) -> None: ...
    def setAllChecked(self, checked = ...) -> None: ...
    def clearChecked(self): ...
    def buildRowActionsMenu(self, srcRow): ...
    def setFilterText(self, text) -> None: ...
    def sortBy(self, column, order = ...): ...
    def pageCount(self): ...
    def currentPage(self): ...
    def setPage(self, index) -> None: ...
    def nextPage(self): ...
    def prevPage(self): ...
    def selectedRows(self): ...
    def customizeQCustomDataTable(self, **customValues): ...
