# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from Custom_Widgets.components.python.ui_tooltip import Ui_Form
from PySide6.QtCore import QObject, Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomQToolTip(QWidget, Ui_Form):
    onClosed: ClassVar[Signal]
    def __init__(self, text: str, parent = ..., target = ..., duration = ..., icon = ..., tailPosition = ...) -> None: ...
    def handleThemeChanged(self): ...
    def setShadowEffect(self) -> None: ...
    def enterEvent(self, event): ...
    def showEvent(self, e): ...
    def closeEvent(self, e): ...
    def eventFilter(self, obj, e: Any): ...
    def paintEvent(self, e: Any): ...
    def setIcon(self, icon) -> None: ...
    def setText(self, text) -> None: ...
    def adjustSizeToContent(self): ...


class QCustomQToolTipManager(QObject):
    def __init__(self) -> None: ...
    @classmethod
    def register(tipOverlay, name): ...
    @classmethod
    def make(tipOverlay, position: str): ...


class TopTailQCustomQToolTipManager(QCustomQToolTipManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class BottomTailQCustomQToolTipManager(QCustomQToolTipManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class LeftTailQCustomQToolTipManager(QCustomQToolTipManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class RightTailQCustomQToolTipManager(QCustomQToolTipManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class TopLeftTailQCustomQToolTipManager(TopTailQCustomQToolTipManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class TopRightTailQCustomQToolTipManager(TopTailQCustomQToolTipManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class BottomLeftTailQCustomQToolTipManager(BottomTailQCustomQToolTipManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class BottomRightTailQCustomQToolTipManager(BottomTailQCustomQToolTipManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class LeftTopTailQCustomQToolTipManager(LeftTailQCustomQToolTipManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class LeftBottomTailQCustomQToolTipManager(LeftTailQCustomQToolTipManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class RightTopTailQCustomQToolTipManager(RightTailQCustomQToolTipManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class RightBottomTailQCustomQToolTipManager(RightTailQCustomQToolTipManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...


class AutoPositionQCustomQToolTipManager(QCustomQToolTipManager):
    def draw(self, tipOverlay, painter, path): ...
    def position(self, tipOverlay: Any): ...
    def createManager(self, tipOverlay: Any): ...
    def getTipOverlay(self, tipOverlay: Any): ...


class QCustomQToolTipFilter(QObject):
    def __init__(self, parent = ..., duration = ..., icon = ..., tailPosition = ...) -> None: ...
    def eventFilter(self, obj, event): ...
    def showCustomToolTip(self, text, target): ...
