# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import QAbstractTableModel, Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class DataTableColumn(object):
    def __init__(self, key, title = ..., type = ..., width = ..., align = ..., formatter = ..., sortable = ...) -> None: ...
    @classmethod
    def ensure(cls, column): ...
    def defaultAlign(self): ...


class QCustomDataTableModel(QAbstractTableModel):
    def __init__(self, columns = ..., rows = ..., parent = ...) -> None: ...
    def rowCount(self, parent = ...): ...
    def columnCount(self, parent = ...): ...
    def data(self, index, role = ...): ...
    def headerData(self, section, orientation, role = ...): ...
    def flags(self, index): ...
    def removeRows(self, row, count, parent = ...): ...
    def columns(self): ...
    def setColumns(self, columns) -> None: ...
    def rows(self): ...
    def setRows(self, rows) -> None: ...
    def addRow(self, row): ...
    def addRows(self, rows): ...
    def clear(self): ...
    def rawValue(self, row, col): ...


class QCustomDataTable(QWidget):
    rowSelected: ClassVar[Signal]
    cellClicked: ClassVar[Signal]
    sortChanged: ClassVar[Signal]
    pageChanged: ClassVar[Signal]
    pageSize: int
    showPagination: Any
    selectionMode: str
    sortable: Any
    filterable: Any
    alternatingRowColors: Any
    showGrid: Any
    showHeader: Any
    variant: str
    sizeVariant: str
    def __init__(self, parent = ...) -> None: ...
    def setColumns(self, columns) -> None: ...
    def setData(self, rows) -> None: ...
    def setRows(self, rows) -> None: ...
    def addRow(self, row): ...
    def clear(self): ...
    def model(self): ...
    def view(self): ...
    def setFilterText(self, text) -> None: ...
    def sortBy(self, column, order = ...): ...
    def pageCount(self): ...
    def currentPage(self): ...
    def setPage(self, index) -> None: ...
    def nextPage(self): ...
    def prevPage(self): ...
    def selectedRows(self): ...
    def customizeQCustomDataTable(self, **customValues): ...
