# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomRangeSlider(QWidget):
    valuesChanged: ClassVar[Signal]
    minimum: int
    maximum: int
    lowerValue: int
    upperValue: int
    trackColor: Any
    fillColor: Any
    handleColor: Any
    handleBorderColor: Any
    def __init__(self, parent = ..., minimum = ..., maximum = ...) -> None: ...
    def paintEvent(self, e): ...
    def mousePressEvent(self, e): ...
    def mouseMoveEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
    def setRange(self, minimum, maximum) -> None: ...
    def setValues(self, lower, upper) -> None: ...
    def values(self): ...
    def setLowerValue(self, v) -> None: ...
    def setUpperValue(self, v) -> None: ...
