# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomNodeGraph(QWidget):
    nodeMoved: ClassVar[Signal]
    nodeSelected: ClassVar[Signal]
    nodeClicked: ClassVar[Signal]
    connectionMade: ClassVar[Signal]
    connectionRemoved: ClassVar[Signal]
    canvasClicked: ClassVar[Signal]
    rowClicked: ClassVar[Signal]
    nodeRemoved: ClassVar[Signal]
    editRequested: ClassVar[Signal]
    bgColor: str
    gridColor: str
    gridSpacing: int
    nodeColor: str
    nodeHeaderColor: str
    nodeBorderColor: str
    textColor: str
    mutedColor: str
    portColor: str
    edgeColor: str
    selectedColor: str
    cornerRadius: int
    animated: bool
    def __init__(self, parent = ...) -> None: ...
    def addNode(self, title = ..., x = ..., y = ..., w = ..., h = ..., accent = ..., text = ..., rows = ..., image = ..., chips = ..., inputs = ..., outputs = ..., nid = ...): ...
    def addEdge(self, src, src_port, dst, dst_port, color = ...): ...
    def clear(self): ...
    def setGraph(self, data) -> None: ...
    def nodeById(self, nid): ...
    def setNodePosition(self, nid, x, y) -> None: ...
    def nodeRows(self, nid): ...
    def setRowValue(self, nid, idx, value) -> None: ...
    def nodeTitle(self, nid): ...
    def setNodeTitle(self, nid, title) -> None: ...
    def nodeText(self, nid): ...
    def setNodeText(self, nid, text) -> None: ...
    def removeNode(self, nid): ...
    def removeEdgeAt(self, index): ...
    def removeEdge(self, src, src_port, dst, dst_port): ...
    def disconnectNode(self, nid): ...
    def fitToView(self, margin = ...): ...
    def paintEvent(self, e): ...
    def mousePressEvent(self, e): ...
    def keyPressEvent(self, e): ...
    def contextMenuEvent(self, e): ...
    def mouseMoveEvent(self, e): ...
    def leaveEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
    def wheelEvent(self, e): ...
    def sizeHint(self): ...
