# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomCopyButton(QWidget):
    copied: ClassVar[Signal]
    payload: str
    text: str
    copiedText: str
    resetDelay: int
    variant: str
    iconOnly: bool
    accentColor: str
    successColor: str
    textColor: str
    surfaceColor: str
    def __init__(self, parent = ..., payload = ..., text = ...) -> None: ...
    def copy(self): ...
    def isConfirming(self): ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def paintEvent(self, e): ...
    def enterEvent(self, e): ...
    def leaveEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
    def keyPressEvent(self, e): ...
