# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomVerificationCode(QWidget):
    codeChanged: ClassVar[Signal]
    completed: ClassVar[Signal]
    code: str
    digits: int
    inputMode: str
    masked: bool
    uppercase: bool
    separatorAfter: int
    boxWidth: int
    boxHeight: int
    boxSpacing: int
    state: str
    boxBackgroundColor: Any
    boxBorderColor: Any
    boxBorderActiveColor: Any
    boxBorderErrorColor: Any
    textColor: Any
    def __init__(self, parent = ..., digits = ..., inputMode = ...) -> None: ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def paintEvent(self, e): ...
    def keyPressEvent(self, e): ...
    def setCodeText(self, text) -> None: ...
    def pasteFromClipboard(self): ...
    def clear(self): ...
    def isComplete(self): ...
    def mousePressEvent(self, e): ...
    def focusInEvent(self, e): ...
    def focusOutEvent(self, e): ...
