# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomImageViewer(QWidget):
    indexChanged: ClassVar[Signal]
    closed: ClassVar[Signal]
    scrimColor: str
    buttonColor: str
    buttonIconColor: str
    textColor: str
    imageRadius: int
    def __init__(self, parent = ...) -> None: ...
    def setImages(self, images) -> None: ...
    def setImageAt(self, index, pm) -> None: ...
    def count(self): ...
    def index(self): ...
    def setIndex(self, i) -> None: ...
    def openAt(self, index, host = ...): ...
    def resizeEvent(self, e): ...
    def paintEvent(self, e): ...
    def mousePressEvent(self, e): ...
    def keyPressEvent(self, e): ...
    def closeEvent(self, e): ...
