# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomPopover(QWidget):
    opened: ClassVar[Signal]
    closed: ClassVar[Signal]
    panelColor: Any
    borderColor: Any
    def __init__(self, anchor = ..., placement = ...) -> None: ...
    def contentLayout(self): ...
    def addWidget(self, widget): ...
    def setPlacement(self, placement) -> None: ...
    def showPopover(self): ...
    def hideEvent(self, e): ...
    def paintEvent(self, e): ...
    @staticmethod
    def attach(trigger, placement = ...): ...
