# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomComponent(QWidget):
    jsonStylesheetFilePath: Any
    def __init__(self, parent = ...) -> None: ...
    def startFileMonitor(self): ...
    def closeEvent(self, event): ...
    def resizeEvent(self, e): ...
    def paintEvent(self, event: Any): ...
