# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomProgressRing(QWidget):
    valueChanged: ClassVar[Signal]
    minimum: int
    maximum: int
    showText: bool
    ringColor: Any
    trackColor: Any
    textColor: Any
    thickness: Any
    def __init__(self, parent = ..., minimum = ..., maximum = ..., value = ...) -> None: ...
    def paintEvent(self, e): ...
    def value(self): ...
    def setValue(self, value) -> None: ...
    def setRange(self, minimum, maximum) -> None: ...
    def setMinimum(self, m) -> None: ...
    def setMaximum(self, m) -> None: ...
    def setShowText(self, show) -> None: ...
