# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomColorPicker(QWidget):
    colorChanged: ClassVar[Signal]
    def __init__(self, parent = ..., color = ...) -> None: ...
    def color(self): ...
    def colorName(self): ...
    def setColor(self, color) -> None: ...
