# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QPushButton
from typing import Any, ClassVar


class QCustomQPushButtonGroup(QPushButton):
    def __init__(self, parent = ...) -> None: ...
    def getButtonGroup(self): ...
    def getButtonGroupActiveStyle(self): ...
    def getButtonGroupNotActiveStyle(self): ...
    def getButtonGroupButtons(self): ...
    def setButtonGroupActiveStyle(self, style) -> None: ...
    def setButtonGroupNotActiveStyle(self, style) -> None: ...
