# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QPushButton
from typing import Any, ClassVar


class QCustomSidebarButton(QPushButton):
    clicked: ClassVar[Signal]
    iconColor: Any
    iconColorActive: Any
    hideOnCollapse: Any
    showOnCollapse: Any
    textPrefixSpaces: Any
    labelHidden: Any
    labelText: Any
    def __init__(self, parent = ..., *args) -> None: ...
    def setIconSize(self, size): ...
    def paintEvent(self, event: Any): ...
    def setText(self, text): ...
    def update(self): ...
    def getPrefixedText(self, text): ...
    def connectToParent(self): ...
    def hideButtonLabel(self): ...
    def hideButtonIcon(self): ...
    def showButtonLabel(self): ...
    def showButtonIcon(self): ...
    def showEvent(self, e): ...
    def enterEvent(self, event: Any): ...
    def leaveEvent(self, event): ...
    def deleteFloatingButton(self, e): ...
    def showFloatingButton(self): ...
    def createFloatingButton(self): ...
    def fadeInFloatingButton(self): ...
    def fadeOutFloatingButton(self): ...
    def hideFloatingButton(self): ...
    def calculateFloatingPosition(self): ...
    def resizeEvent(self, event): ...
    def moveEvent(self, event): ...
    def eventFilter(self, obj, event: Any): ...
    def setNewIcon(self, url): ...
