# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QStackedWidget
from typing import Any, ClassVar


class QCustomQStackedWidget(QStackedWidget):
    transitionFinished: ClassVar[Signal]
    fadeTransition: Any
    slideTransition: Any
    transitionDirection: Any
    transitionTime: Any
    fadeTime: Any
    fadeDelay: Any
    fadeInTime: Any
    fadeOutTime: Any
    fadeInCurve: Any
    fadeOutCurve: Any
    transitionEasingCurve: Any
    fadeEasingCurve: Any
    def __init__(self, parent = ...) -> None: ...
    def setSlideTransition(self, slideState = ...) -> None: ...
    def setFadeTransition(self, fadeState = ...) -> None: ...
    def setTransitionDirection(self, direction) -> None: ...
    def setTransitionSpeed(self, speed) -> None: ...
    def setFadeSpeed(self, speed) -> None: ...
    def setFadeDelay(self, delay) -> None: ...
    def setFadeInOutTimes(self, fadeInTime, fadeOutTime) -> None: ...
    def setFadeInOutCurves(self, fadeInCurve, fadeOutCurve) -> None: ...
    def setTransitionEasingCurve(self, aesingCurve) -> None: ...
    def setFadeCurve(self, aesingCurve) -> None: ...
    def slideToPreviousWidget(self): ...
    def slideToNextWidget(self): ...
    def slideToWidgetIndex(self, index): ...
    def slideToWidget(self, newWidget): ...
    def setCurrentWidget(self, widget): ...
    def setCurrentIndex(self, index): ...
    def paintEvent(self, event): ...
    def addWidget(self, widget): ...
