# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomGradientPicker(QWidget):
    gradientChanged: ClassVar[Signal]
    stopSelected: ClassVar[Signal]
    stopsCsv: str
    gradientType: str
    angle: int
    barHeight: int
    handleRadius: int
    readOnly: bool
    state: str
    borderColor: Any
    borderActiveColor: Any
    borderErrorColor: Any
    handleColor: Any
    handleBorderColor: Any
    def __init__(self, parent = ..., stops = ..., gradientType = ...) -> None: ...
    def setStops(self, stops) -> None: ...
    def stops(self): ...
    def count(self): ...
    def addStop(self, position, colour = ...): ...
    def removeStop(self, index): ...
    def setStopColor(self, index, colour) -> None: ...
    def setStopPosition(self, index, position) -> None: ...
    def stopColor(self, index): ...
    def stopPosition(self, index): ...
    def selectedIndex(self): ...
    def setSelectedIndex(self, index) -> None: ...
    def colorAt(self, position): ...
    def gradient(self, rect = ...): ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def handleAt(self, point): ...
    def paintEvent(self, e): ...
    def mousePressEvent(self, e): ...
    def mouseMoveEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
    def mouseDoubleClickEvent(self, e): ...
    def editStopColor(self, index = ...): ...
    def keyPressEvent(self, e): ...
