# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QLayout
from typing import Any, ClassVar


class AnimatedWidgetItem(object):
    def __init__(self, widget, targetGeometry) -> None: ...
    def start(self): ...


class QCustomFlowLayout(QLayout):
    animationStarted: ClassVar[Signal]
    animationFinished: ClassVar[Signal]
    def __init__(self, parent = ..., margin = ..., spacing = ..., animate = ..., animationDuration = ...) -> None: ...
    def loadOrderFromJson(self): ...
    def addItem(self, a0: Any): ...
    def addWidget(self, w: Any, position: int = ..., align: Any = ...): ...
    def count(self): ...
    def expandingDirections(self): ...
    def itemAt(self, index: int): ...
    def hasHeightForWidth(self): ...
    def heightForWidth(self, width): ...
    def minimumSize(self): ...
    def removeItem(self, a0: Any): ...
    def removeWidget(self, w: Any): ...
    def setGeometry(self, rect): ...
    def sizeHint(self): ...
    def takeAt(self, index: int): ...
    def setAnimated(self, animate) -> None: ...
    def setAnimationDuration(self, durationMs) -> None: ...
    def setAnimationEasingCurve(self, curve) -> None: ...
    def stopAllAnimations(self): ...
    def isAnimating(self): ...
