# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomAccordion(QWidget):
    sectionToggled: ClassVar[Signal]
    def __init__(self, parent = ..., exclusive = ...) -> None: ...
    def addSection(self, title, content): ...
    def sectionCount(self): ...
    def section(self, index): ...
    def setExpanded(self, index, expanded, animate = ...) -> None: ...
    def expandedIndices(self): ...
    def setExclusive(self, exclusive) -> None: ...
    def isExclusive(self): ...
