# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomCarousel(QWidget):
    currentChanged: ClassVar[Signal]
    currentIndex_: Any
    wrap: bool
    def __init__(self, parent = ..., wrap = ...) -> None: ...
    def addSlide(self, widget): ...
    def insertSlide(self, index, widget): ...
    def removeSlide(self, index): ...
    def clear(self): ...
    def count(self): ...
    def currentIndex(self): ...
    def setCurrentIndex(self, index) -> None: ...
    def next(self): ...
    def previous(self): ...
    def setWrap(self, wrap) -> None: ...
    def wrapsAround(self): ...
    def setAutoAdvance(self, milliseconds) -> None: ...
