# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomCoverFlow(QWidget):
    currentChanged: ClassVar[Signal]
    itemClicked: ClassVar[Signal]
    playClicked: ClassVar[Signal]
    itemsJson: str
    currentIndex: int
    activeRatio: float
    aspect: float
    sideScale: float
    sideOpacity: float
    sideSpacing: float
    cornerRadius: int
    showText: bool
    showPlay: bool
    titleColor: str
    artistColor: str
    playColor: str
    def __init__(self, parent = ...) -> None: ...
    def setItems(self, items) -> None: ...
    def count(self): ...
    def setCurrentIndex(self, i, animate = ...) -> None: ...
    def next(self): ...
    def previous(self): ...
    def paintEvent(self, e): ...
    def mousePressEvent(self, e): ...
    def mouseMoveEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
    def wheelEvent(self, e): ...
    def keyPressEvent(self, e): ...
    def sizeHint(self): ...
