# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomFeaturedIcon(QWidget):
    clicked: ClassVar[Signal]
    iconPath: str
    shape: str
    variant: str
    sizeVariant: str
    cornerRadius: int
    accentColor: str
    iconColor: str
    surfaceColor: str
    def __init__(self, parent = ..., icon = ..., variant = ..., shape = ...) -> None: ...
    def setIcon(self, icon) -> None: ...
    def icon(self): ...
    def hasIcon(self): ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def paintEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
