# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomModal(QWidget):
    triggered: ClassVar[Signal]
    closed: ClassVar[Signal]
    def __init__(self, parent = ...) -> None: ...
    def clearContent(self): ...
    def clearActions(self): ...
    def setTitle(self, text) -> None: ...
    def setSubtitle(self, text) -> None: ...
    def addContent(self, widget): ...
    def addAction(self, text, key = ..., primary = ..., danger = ...): ...
    def showModal(self): ...
    def closeModal(self): ...
    def paintEvent(self, e): ...
    def mousePressEvent(self, e): ...
    def keyPressEvent(self, e): ...
    def resizeEvent(self, e): ...
    def eventFilter(self, obj, ev): ...
    def applyColors(self, bg = ..., text = ..., muted = ..., border = ..., accent = ..., accentText = ..., hover = ...): ...
