# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomCandlestickChart(QWidget):
    candleHovered: ClassVar[Signal]
    candleClicked: ClassVar[Signal]
    ohlcCsv: str
    labelsCsv: str
    showGrid: bool
    showPriceAxis: bool
    showLabels: bool
    showTooltip: bool
    hollowUpCandles: bool
    candleWidthRatio: float
    gridLines: int
    pricePrecision: int
    upColor: str
    downColor: str
    wickColor: str
    gridColor: str
    axisTextColor: str
    tooltipBackgroundColor: Any
    tooltipTextColor: Any
    def __init__(self, parent = ..., data = ..., labels = ...) -> None: ...
    def setData(self, data, labels = ...) -> None: ...
    def data(self): ...
    def count(self): ...
    def setLabels(self, labels) -> None: ...
    def labels(self): ...
    def priceRange(self): ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def paintEvent(self, e): ...
    def candleAt(self, pos): ...
    def mouseMoveEvent(self, e): ...
    def leaveEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
