# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomHeaderNav(QWidget):
    itemSelected: ClassVar[Signal]
    brandClicked: ClassVar[Signal]
    overflowClicked: ClassVar[Signal]
    indicatorPos: Any
    itemsCsv: str
    brandText: str
    currentKey: str
    indicator: str
    alignment: str
    itemSpacing: int
    barHeight: int
    animated: bool
    showDivider: bool
    accentColor: str
    textColor: str
    activeTextColor: str
    surfaceColor: str
    dividerColor: str
    def __init__(self, parent = ..., items = ..., brand = ...) -> None: ...
    def setItems(self, items) -> None: ...
    def items(self): ...
    def count(self): ...
    def labelFor(self, key): ...
    def currentIndex(self): ...
    def setCurrentIndex(self, index, animate = ...) -> None: ...
    def setCurrentKey(self, key, animate = ...) -> None: ...
    def currentKeyValue(self): ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def itemRects(self): ...
    def hiddenCount(self): ...
    def resizeEvent(self, e): ...
    def paintEvent(self, e): ...
    def itemAt(self, pos): ...
    def mouseMoveEvent(self, e): ...
    def leaveEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
