# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomBubbleChart(QWidget):
    bubbleClicked: ClassVar[Signal]
    searchRequested: ClassVar[Signal]
    zoomChanged: ClassVar[Signal]
    itemsJson: str
    categoriesJson: str
    padding: float
    showLabels: bool
    minLabelRadius: float
    labelColor: str
    defaultColor: str
    shadeVariation: float
    hoverGlow: bool
    hoverScale: float
    groupByCategory: bool
    zoomable: bool
    showControls: bool
    searchQuery: str
    tooltips: bool
    tooltipBgColor: str
    controlColor: str
    def __init__(self, parent = ..., items = ...) -> None: ...
    def setItems(self, items) -> None: ...
    def setCategoryColors(self, mapping) -> None: ...
    def setSearchQuery(self, text) -> None: ...
    def items(self): ...
    def zoomIn(self): ...
    def zoomOut(self): ...
    def resetView(self): ...
    def paintEvent(self, e): ...
    def mousePressEvent(self, e): ...
    def mouseMoveEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
    def mouseDoubleClickEvent(self, e): ...
    def wheelEvent(self, e): ...
    def leaveEvent(self, e): ...
    def resizeEvent(self, e): ...
