# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomSparklesText(QWidget):
    clicked: ClassVar[Signal]
    text: str
    sparkleCount: int
    sparkleSize: float
    speed: int
    animated: bool
    seed: int
    fontScale: float
    bold: bool
    colorsCsv: str
    textColor: str
    def __init__(self, parent = ..., text = ..., sparkleCount = ...) -> None: ...
    def sparkles(self): ...
    def setColors(self, colors) -> None: ...
    def colors(self): ...
    def start(self): ...
    def stop(self): ...
    def isAnimating(self): ...
    def showEvent(self, e): ...
    def hideEvent(self, e): ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def paintEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
