# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QFrame
from typing import Any, ClassVar


class ArcLoader(object):
    def __init__(self, parent = ..., spacer = ..., startAngle = ..., spanAngle = ..., direction = ..., duration = ...) -> None: ...
    def getRotationAnimation(self): ...
    def getSpanAngleAnimation(self): ...
    def getStartAngleAnimation(self): ...
    def startAnimationFinished(self): ...
    def startAnimations(self): ...
    def animationFinished(self): ...
    def updateStartAngle(self, newValue): ...
    def updateSpacer(self, newValue): ...
    def updateSpanAngle(self, newValue): ...


class QCustomArcLoader(QFrame):
    color: Any
    penWidth: Any
    def __init__(self, parent = ..., color = ..., penWidth = ...) -> None: ...
    def calculateXR(self, level): ...
    def draw(self): ...
    def initPen(self, penWidth): ...
    def paintEvent(self, e): ...
