# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomChip(QWidget):
    removed: ClassVar[Signal]
    clicked: ClassVar[Signal]
    toggled: ClassVar[Signal]
    def __init__(self, text, closable = ..., selectable = ..., data = ..., parent = ...) -> None: ...
    def resizeEvent(self, e): ...
    def text(self): ...
    def data(self): ...
    def isSelected(self): ...
    def setSelected(self, selected) -> None: ...
    def mousePressEvent(self, e): ...


class QCustomChipGroup(QWidget):
    chipRemoved: ClassVar[Signal]
    selectionChanged: ClassVar[Signal]
    def __init__(self, parent = ..., selectable = ..., exclusive = ..., closable = ...) -> None: ...
    def addChip(self, text, data = ..., closable = ..., selectable = ...): ...
    def setChips(self, texts) -> None: ...
    def chips(self): ...
    def selectedChips(self): ...
    def selectedData(self): ...
    def count(self): ...
