# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomDrawer(QWidget):
    opened: ClassVar[Signal]
    closed: ClassVar[Signal]
    def __init__(self, parent, side = ..., size = ...) -> None: ...
    def contentLayout(self): ...
    def addWidget(self, widget): ...
    def open(self): ...
    def close(self): ...
    def isOpen(self): ...
    def mousePressEvent(self, e): ...
    def keyPressEvent(self, e): ...
