# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QAbstractButton
from typing import Any, ClassVar


class QCustomCoverCard(QAbstractButton):
    playClicked: ClassVar[Signal]
    title: str
    artist: str
    coverPath: str
    accentColor: str
    titleColor: str
    artistColor: str
    cornerRadius: int
    scrimStrength: float
    scrimColor: str
    showPlay: bool
    playOnHover: bool
    titleScale: float
    textAlign: str
    def __init__(self, parent = ..., title = ..., artist = ..., coverPath = ...) -> None: ...
    def setTitle(self, text) -> None: ...
    def setArtist(self, text) -> None: ...
    def setCoverPath(self, path) -> None: ...
    def setData(self, title = ..., artist = ..., coverPath = ...) -> None: ...
    def paintEvent(self, e): ...
    def mouseMoveEvent(self, e): ...
    def enterEvent(self, e): ...
    def leaveEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
    def sizeHint(self): ...
