# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomRadarChart(QWidget):
    seriesHovered: ClassVar[Signal]
    axisClicked: ClassVar[Signal]
    axesCsv: str
    seriesCsv: str
    seriesColorsCsv: str
    maxValue: float
    rings: int
    gridStyle: str
    startAngle: int
    fillOpacity: float
    lineWidth: float
    showAxisLabels: bool
    showRingLabels: bool
    showMarkers: bool
    showLegend: bool
    gridColor: str
    axisColor: str
    labelColor: str
    def __init__(self, parent = ..., axes = ..., series = ...) -> None: ...
    def setAxes(self, labels) -> None: ...
    def axes(self): ...
    def axisCount(self): ...
    def addSeries(self, name, values, color = ...): ...
    def setSeries(self, series) -> None: ...
    def series(self): ...
    def seriesCount(self): ...
    def removeSeries(self, index): ...
    def clearSeries(self): ...
    def seriesColor(self, index): ...
    def maximum(self): ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def paintEvent(self, e): ...
    def seriesAt(self, pos): ...
    def axisAt(self, pos): ...
    def mouseMoveEvent(self, e): ...
    def leaveEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
