# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomPaymentCard(QWidget):
    numberRevealed: ClassVar[Signal]
    brand: str
    amount: str
    number: str
    variant: str
    gradientStart: str
    gradientEnd: str
    flatColor: str
    textColor: str
    cornerRadius: int
    showChip: bool
    fullNumber: str
    revealable: bool
    revealed: Any
    def __init__(self, parent = ..., brand = ..., amount = ..., number = ...) -> None: ...
    def setBrand(self, text) -> None: ...
    def setAmount(self, text) -> None: ...
    def setNumber(self, text) -> None: ...
    def setColors(self, start, end = ...) -> None: ...
    def setVariant(self, variant) -> None: ...
    def setFullNumber(self, number) -> None: ...
    def setRevealable(self, on) -> None: ...
    def setRevealed(self, on) -> None: ...
    def toggleReveal(self): ...
    def paintEvent(self, e): ...
    def mousePressEvent(self, e): ...
