# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomDateRangePicker(QWidget):
    rangeChanged: ClassVar[Signal]
    monthsVisible: int
    accentColor: str
    rangeBandColor: str
    todayColor: str
    textColor: str
    mutedColor: str
    headerColor: str
    selectedTextColor: str
    def __init__(self, parent = ..., start = ..., end = ..., monthsVisible = ...) -> None: ...
    def setStartDate(self, d) -> None: ...
    def setEndDate(self, d) -> None: ...
    def setRange(self, start, end) -> None: ...
    def setSelectableRange(self, minimum, maximum) -> None: ...
    def setMonthsVisible(self, n) -> None: ...
    def startDate(self): ...
    def endDate(self): ...
    def showMonth(self, year, month): ...
    def paintEvent(self, e): ...
    def mousePressEvent(self, e): ...
    def sizeHint(self): ...
