# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import QObject, Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomFormField(QObject):
    def __init__(self, label, parent = ..., widget = ...) -> None: ...
    def set_required(self, required) -> None: ...
    def set_validator(self, validator) -> None: ...
    def set_value(self, value) -> None: ...
    def value(self): ...
    def validate(self): ...


class QCustomForm(QWidget):
    submitted: ClassVar[Signal]
    def __init__(self, parent = ...) -> None: ...
    def add_field(self, field): ...
    def validate(self): ...
    def errors(self): ...
    def submit(self): ...
