# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomNumberInput(QWidget):
    valueChanged: ClassVar[Signal]
    minimum: Any
    maximum: Any
    singleStep: Any
    decimals: int
    def __init__(self, parent = ..., minimum = ..., maximum = ..., value = ..., step = ..., decimals = ...) -> None: ...
    def value(self): ...
    def setValue(self, value) -> None: ...
    def stepUp(self): ...
    def stepDown(self): ...
    def setRange(self, minimum, maximum) -> None: ...
    def setMinimum(self, minimum) -> None: ...
    def setMaximum(self, maximum) -> None: ...
    def setSingleStep(self, step) -> None: ...
    def setDecimals(self, decimals) -> None: ...
    def lineEdit(self): ...
