# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class Command(object):
    def __init__(self, id, title, callback = ..., subtitle = ..., shortcut = ..., category = ...) -> None: ...
    @classmethod
    def ensure(cls, item): ...


class QCustomCommandPalette(QWidget):
    commandTriggered: ClassVar[Signal]
    def __init__(self, parent) -> None: ...
    def setCommands(self, commands) -> None: ...
    def addCommand(self, *args, **kw): ...
    def open(self): ...
    def close(self): ...
    def mousePressEvent(self, e): ...
    @staticmethod
    def installShortcut(window, sequence = ..., commands = ...): ...
