# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomStatCard(QWidget):
    label: str
    value: str
    caption: str
    trend: str
    def __init__(self, parent = ..., label = ..., value = ..., delta = ..., trend = ..., caption = ...) -> None: ...
    def setLabel(self, text) -> None: ...
    def setValue(self, text) -> None: ...
    def setCaption(self, text) -> None: ...
    def setDelta(self, text, trend = ...) -> None: ...
    def setTrend(self, trend) -> None: ...
