# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomRadioGroup(QWidget):
    valueChanged: ClassVar[Signal]
    currentIndexChanged: ClassVar[Signal]
    optionsCsv: str
    selectedValue: str
    title: str
    orientation: str
    spacingPx: int
    sizeVariant: str
    titleColor: Any
    def __init__(self, parent = ..., options = ..., value = ..., orientation = ..., title = ...) -> None: ...
    def setOptions(self, options) -> None: ...
    def options(self): ...
    def buttons(self): ...
    def count(self): ...
    def value(self): ...
    def setValue(self, value) -> None: ...
    def currentIndex(self): ...
    def setCurrentIndex(self, index) -> None: ...
    def currentLabel(self): ...
    def clearSelection(self): ...
    def paintEvent(self, e): ...
