# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomSidebarLabel(QWidget):
    visibilityChanged: ClassVar[Signal]
    text: Any
    icon: Any
    iconSize: Any
    hideOnCollapse: Any
    showOnCollapse: Any
    def __init__(self, parent = ...) -> None: ...
    def start_show_animation(self): ...
    def start_hide_animation(self): ...
    def on_animation_finished(self): ...
    def hideLabel(self): ...
    def showLabel(self): ...
    def showEvent(self, e): ...
    def validateIconAndLabel(self): ...
    def setText(self, new_text: str) -> None: ...
    def setIcon(self, icon: Any) -> None: ...
    def connect_to_parent(self): ...
    def paintEvent(self, event: Any): ...
    def setNewIcon(self, url) -> None: ...
