# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomImagePicker(QWidget):
    imageSelected: ClassVar[Signal]
    imageCleared: ClassVar[Signal]
    selectionRejected: ClassVar[Signal]
    imagePath: str
    placeholderText: str
    shape: str
    fitMode: str
    maxBytes: int
    maxPixels: int
    allowClear: bool
    cornerRadius: int
    state: str
    borderColor: Any
    borderActiveColor: Any
    borderErrorColor: Any
    backgroundColor: Any
    textColor: Any
    def __init__(self, parent = ..., path = ..., placeholder = ...) -> None: ...
    def validationError(self, path): ...
    def canAccept(self, path): ...
    def setImagePath(self, path) -> None: ...
    def pixmap(self): ...
    def hasImage(self): ...
    def clearImage(self): ...
    def browse(self): ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def paintEvent(self, e): ...
    def dragEnterEvent(self, e): ...
    def dragLeaveEvent(self, e): ...
    def dropEvent(self, e): ...
    def enterEvent(self, e): ...
    def leaveEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
    def keyPressEvent(self, e): ...
