# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QCheckBox
from typing import Any, ClassVar


class QCustomCheckBox(QCheckBox):
    backgroundColor: Any
    circleColor: Any
    activeColor: Any
    animationDuration: Any
    animationEasingCurve: Any
    position: Any
    def __init__(self, parent = ...) -> None: ...
    def setIcon(self, icon): ...
    def setIconSize(self, size): ...
    def customizeQCustomCheckBox(self, **customValues): ...
    def showEvent(self, e): ...
    def resizeEvent(self, event): ...
    def adjustWidgetSize(self): ...
    def setText(self, text): ...
    def setup_animation(self, value) -> None: ...
    def hitButton(self, pos: Any): ...
    def paintEvent(self, e: Any): ...
    def setNewIcon(self, url): ...
