# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomVerticalSeparator(QWidget):
    color: Any
    width: Any  # type: ignore[assignment]
    margin: Any
    def __init__(self, parent = ..., color = ..., width = ..., margin = ...) -> None: ...
    def getColor(self): ...
    def setColor(self, color) -> None: ...
    def getWidth(self): ...
    def setWidth(self, width) -> None: ...
    def getMargin(self): ...
    def setMargin(self, margin) -> None: ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def paintEvent(self, event): ...
