# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomTableToolbar(QWidget):
    searchChanged: ClassVar[Signal]
    filtersClicked: ClassVar[Signal]
    filterChipRemoved: ClassVar[Signal]
    clearFiltersClicked: ClassVar[Signal]
    statusSelected: ClassVar[Signal]
    showStatusesToggled: ClassVar[Signal]
    def __init__(self, parent = ...) -> None: ...
    def searchInput(self): ...
    def setSearchPlaceholder(self, text) -> None: ...
    def searchText(self): ...
    def setSearchText(self, text) -> None: ...
    def setFilterChips(self, items) -> None: ...
    def addFilterChip(self, key, label, value = ...): ...
    def removeFilterChip(self, key): ...
    def clearFilterChips(self): ...
    def filterChipKeys(self): ...
    def setStatuses(self, items) -> None: ...
    def setStatusCount(self, key, count) -> None: ...
    def setActiveStatus(self, key) -> None: ...
    def activeStatus(self): ...
    def showStatuses(self): ...
    def setShowStatuses(self, on) -> None: ...
    def setThemeColors(self, surface = ..., on_surface = ..., muted = ..., outline = ..., accent = ...) -> None: ...
