# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomMenu(QWidget):
    triggered: ClassVar[Signal]
    def __init__(self, parent = ...) -> None: ...
    def addAction(self, text, key = ..., icon = ..., hint = ..., danger = ...): ...
    def addSeparator(self): ...
    def clear(self): ...
    def applyColors(self, bg = ..., text = ..., muted = ..., hover = ..., border = ..., accent = ..., danger = ...): ...
    def popupAt(self, anchor, align = ..., gap = ...): ...
    def popupAtPos(self, global_pos): ...
