# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomRangeBarChart(QWidget):
    barHovered: ClassVar[Signal]
    barClicked: ClassVar[Signal]
    rangesCsv: str
    categoriesCsv: str
    orientation: str
    barWidthRatio: float
    cornerRadius: int
    tickCount: int
    showGrid: bool
    showAxis: bool
    showLabels: bool
    showBounds: bool
    barColor: str
    gridColor: str
    labelColor: str
    boundsColor: str
    def __init__(self, parent = ..., ranges = ...) -> None: ...
    def setRanges(self, ranges) -> None: ...
    def ranges(self): ...
    def barCount(self): ...
    def clearRanges(self): ...
    def dataBounds(self): ...
    def valueRange(self): ...
    def sizeHint(self): ...
    def minimumSizeHint(self): ...
    def valueToPixel(self, value): ...
    def barRects(self): ...
    def paintEvent(self, e): ...
    def barAt(self, pos): ...
    def mouseMoveEvent(self, e): ...
    def leaveEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
