# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget
from typing import Any, ClassVar


class QCustomSparkline(QWidget):
    valuesCsv: str
    lineColor: Any
    fillColor: Any
    fillEnabled: bool
    fillOpacity: float
    lineWidth: float
    smooth: bool
    seriesCsv: str
    seriesColorsCsv: str
    def __init__(self, parent = ..., values = ..., lineColor = ...) -> None: ...
    def setValues(self, values) -> None: ...
    def values(self): ...
    def clear(self): ...
    def setSeries(self, series, colors = ...) -> None: ...
    def setSeriesColors(self, colors) -> None: ...
    def series(self): ...
    def paintEvent(self, e): ...
