# Auto-generated type stub — DO NOT EDIT.
# Regenerate with:  python -m Custom_Widgets.mcp.stubgen --write
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QPushButton
from typing import Any, ClassVar


class QCustomQPushButton(QPushButton):
    variant: str
    sizeVariant: str
    iconName: str
    iconColor: str
    iconNameActive: str
    iconColorActive: str
    def __init__(self, parent = ...) -> None: ...
    def setIconSize(self, size) -> None: ...
    def setObjectTheme(self, theme) -> None: ...
    def setObjectCustomTheme(self, color1, color2) -> None: ...
    def setObjectAnimation(self, animation) -> None: ...
    def setObjectAnimateOn(self, trigger) -> None: ...
    def setObjectFallBackStyle(self, style) -> None: ...
    def setObjectDefaultStyle(self, style) -> None: ...
    def enterEvent(self, event): ...
    def leaveEvent(self, event): ...
    def mousePressEvent(self, event): ...
    def mouseReleaseEvent(self, event): ...
    def doNothing(self): ...
    def removeButtonShadow(self): ...
    def applyDefaultStyle(self): ...
